#+Title: Arctos

* “Artistic Computing Technologies in Open Science” (ARCTOS)

*Arctos* is a non-profit organisation, I believe that the collaboration between scientists and artists is necessary to develop innovative visual and audible tools for STEAM (Science, Technology, Engineering, Arts and Mathematics) education.

Arctos is also an interdisciplinary project in which a frame of researchers including Prof. Ioannis Zannos and Dr. Fiori-Anastasia Metallinou took part so as to improve the interpretation of scientific data in the fields of Astronomy and Earth Science. In this project we have combined sonification techniques (parameter mapping) with live coding, using various creative-interactive coding environments such as ipython, openFrameworks, and SuperCollider through OSC. The results from the above studies are used for artistic and educational purposes; it was presented in a most attractive way which enhanced the effectiveness of learning. The first results of this project were presented in "Researcher’s Night" in Hellenic-World at Athens in 2017, "AKOUSMATA" AVARTS Festival in Megaron at Athens and published in the 10th Panhellenic Congress of Amateur Astronomy on October 2017. 

